-- Inserción de cuentas Meta Ads para el sistema Nora AI
-- Este archivo contiene los scripts de inserción para la tabla meta_ads_cuentas

-- Nota: Este archivo puede contener datos de ejemplo o inserts específicos
-- para configurar las cuentas publicitarias en el sistema

-- Estructura esperada de la tabla meta_ads_cuentas:
-- CREATE TABLE meta_ads_cuentas (
--     id BIGSERIAL PRIMARY KEY,
--     nombre_nora VARCHAR(50) NOT NULL,
--     id_cuenta_publicitaria VARCHAR(50) NOT NULL,
--     nombre_cliente VARCHAR(200),
--     estado_actual VARCHAR(50) DEFAULT 'ACTIVE',
--     conectada BOOLEAN DEFAULT TRUE,
--     webhook_registrado BOOLEAN DEFAULT FALSE,
--     ultima_sincronizacion TIMESTAMPTZ,
--     creada_en TIMESTAMPTZ DEFAULT NOW(),
--     actualizada_en TIMESTAMPTZ DEFAULT NOW()
-- );

-- Ejemplo de insert (ajustar según datos reales):
-- INSERT INTO meta_ads_cuentas (
--     nombre_nora,
--     id_cuenta_publicitaria, 
--     nombre_cliente,
--     estado_actual,
--     conectada
-- ) VALUES (
--     'aura',
--     'act_123456789',
--     'Cliente Ejemplo',
--     'ACTIVE',
--     true
-- );
