[phases.setup]
nixPkgs = ['python310', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python -m gunicorn run:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info'
