from clientes.aura.routes.panel_cliente_meta_ads import sincronizar as sincronizar_meta_ads_bp

# ...existing code...
def registrar_blueprints_por_nora(app, modulos, nombre_nora):
    # ...existing registration code...

    if "meta_ads" in modulos:
        safe_register_blueprint(app, sincronizar_meta_ads_bp, url_prefix=f"/panel_cliente/{nombre_nora}/meta_ads")

    # ...existing registration code...
# ...existing code...