# Archivo generado automáticamente
# Fecha de generación: 2025-08-14 13:13:29,420
# Total de tablas encontradas: 102
SUPABASE_SCHEMAS = {'JulietDesigns': {'estructura': 'tabla_vacia'},
 'JulietImages': {'estructura': 'tabla_vacia'},
 'JulietPrompts': {'estructura': 'tabla_vacia'},
 'JulietVideos': {'estructura': 'tabla_vacia'},
 'agenda_eventos': {'actualizado_en': 'timestamp',
                    'all_day': 'boolean',
                    'color': 'text',
                    'creado_en': 'timestamp',
                    'descripcion': 'text',
                    'empresa_id': 'nullable',
                    'empresa_uuid': 'nullable',
                    'fecha_fin': 'timestamp',
                    'fecha_inicio': 'timestamp',
                    'frecuencia_recurrencia': 'nullable',
                    'google_calendar_id': 'nullable',
                    'google_event_id': 'nullable',
                    'hasta_fecha': 'nullable',
                    'id': 'integer',
                    'invitados': 'nullable',
                    'nombre_nora': 'text',
                    'recordatorio_minutos': 'nullable',
                    'recurrente': 'boolean',
                    'tarea_id': 'nullable',
                    'tarea_uuid': 'nullable',
                    'tipo': 'text',
                    'tipo_evento': 'text',
                    'titulo': 'text',
                    'todo_el_dia': 'boolean',
                    'ubicacion': 'nullable',
                    'uuid_id': 'text'},
 'alertas': {'acciones': 'nullable',
             'activa': 'boolean',
             'cliente_id': 'nullable',
             'condiciones': 'json',
             'creado_en': 'timestamp',
             'datos': 'json',
             'descripcion': 'text',
             'evento_origen': 'text',
             'id': 'text',
             'nombre': 'text',
             'nombre_nora': 'text',
             'prioridad': 'text',
             'resuelta': 'boolean',
             'resuelta_en': 'nullable',
             'tipo': 'text',
             'vista': 'boolean'},
 'apis_registradas': {'activa': 'boolean',
                      'clave_api': 'text',
                      'created_at': 'timestamp',
                      'descripcion': 'text',
                      'documentacion': 'nullable',
                      'id': 'text',
                      'nombre': 'text',
                      'nora': 'nullable',
                      'updated_at': 'timestamp',
                      'url_base': 'timestamp'},
 'archivos_conocimiento': {'estructura': 'tabla_vacia'},
 'asistencias_cursos': {'estructura': 'tabla_vacia'},
 'automatizaciones': {'activo': 'boolean',
                      'actualizado_en': 'timestamp',
                      'creado_en': 'timestamp',
                      'descripcion': 'text',
                      'frecuencia': 'text',
                      'funcion_objetivo': 'text',
                      'hora_ejecucion': 'text',
                      'id': 'text',
                      'modulo_relacionado': 'text',
                      'nombre': 'text',
                      'parametros_json': 'json',
                      'proxima_ejecucion': 'timestamp',
                      'ultima_ejecucion': 'timestamp'},
 'catalogo_formas_pago': {'created_at': 'timestamp', 'id': 'text', 'nombre': 'text'},
 'categorias_cursos': {'activo': 'boolean',
                       'color_hex': 'text',
                       'descripcion': 'text',
                       'fecha_creacion': 'timestamp',
                       'icono': 'text',
                       'id': 'text',
                       'nombre': 'text',
                       'nombre_nora': 'text',
                       'orden_display': 'integer'},
 'cliente_empresas': {'accesos': 'nullable',
                      'activo': 'boolean',
                      'actualizado_en': 'timestamp',
                      'brief': 'nullable',
                      'ciudad': 'nullable',
                      'cliente_id': 'nullable',
                      'creado_en': 'timestamp',
                      'email_empresa': 'nullable',
                      'email_representante': 'nullable',
                      'estado': 'nullable',
                      'fecha_alta': 'nullable',
                      'fecha_baja': 'nullable',
                      'giro': 'nullable',
                      'id': 'text',
                      'logo_url': 'nullable',
                      'nombre_empresa': 'text',
                      'nombre_nora': 'text',
                      'notas': 'nullable',
                      'pais': 'nullable',
                      'razon_social': 'nullable',
                      'redes': 'nullable',
                      'representante_legal': 'nullable',
                      'rfc': 'nullable',
                      'sitio_web': 'nullable',
                      'telefono_empresa': 'nullable',
                      'telefono_representante': 'nullable',
                      'tipo': 'text',
                      'ubicacion': 'nullable'},
 'clientes': {'acepta_promo': 'boolean',
              'acepta_promos': 'boolean',
              'activo': 'boolean',
              'actualizado_en': 'timestamp',
              'canal_favorito': 'nullable',
              'ciudad': 'text',
              'creado_en': 'timestamp',
              'cumple': 'nullable',
              'email': 'text',
              'estado': 'text',
              'etapa': 'nullable',
              'fecha_baja': 'nullable',
              'fecha_inicio': 'nullable',
              'genero': 'text',
              'id': 'text',
              'idioma': 'nullable',
              'medio_contact': 'text',
              'medio_contacto': 'nullable',
              'nombre_cliente': 'text',
              'nombre_nora': 'text',
              'notas': 'nullable',
              'pais': 'text',
              'puesto': 'text',
              'telefono': 'nullable',
              'tipo': 'text'},
 'configuracion_bot': {'actualizado_en': 'text',
                       'bienvenida': 'text',
                       'correo_cliente': 'text',
                       'creado_en': 'text',
                       'ia_activa': 'boolean',
                       'id': 'text',
                       'instrucciones': 'text',
                       'mensaje_bienvenida': 'text',
                       'mensaje_fuera_tema': 'text',
                       'modo_respuesta': 'text',
                       'modulos': 'json',
                       'nombre_nora': 'text',
                       'nombre_visible': 'text',
                       'numero_nora': 'integer',
                       'password': 'nullable',
                       'personalidad': 'text',
                       'tipo_usuario': 'text',
                       'whatsapp_admin': 'integer'},
 'configuracion_notificaciones': {'actualizado_en': 'timestamp',
                                  'creado_en': 'timestamp',
                                  'email': 'text',
                                  'email_notificaciones': 'boolean',
                                  'id': 'integer',
                                  'nombre_nora': 'text',
                                  'sms_notificaciones': 'boolean',
                                  'solo_alta_prioridad': 'boolean',
                                  'telefono': 'text'},
 'conocimiento_nora': {'activo': 'boolean',
                       'contenido': 'text',
                       'creado_por': 'nullable',
                       'etiquetas': 'array',
                       'fecha_creacion': 'timestamp',
                       'id': 'text',
                       'nombre_nora': 'text',
                       'origen': 'text',
                       'prioridad': 'boolean'},
 'conocimiento_por_servicio': {'estructura': 'tabla_vacia'},
 'contactos': {'actualizado_en': 'timestamp',
               'ciudad': 'nullable',
               'correo': 'nullable',
               'creado_en': 'timestamp',
               'cumpleanos': 'nullable',
               'direccion': 'nullable',
               'empresa': 'nullable',
               'etiquetas_string': 'nullable',
               'id': 'text',
               'imagen_perfil': 'nullable',
               'mensaje_reciente': 'text',
               'nombre': 'text',
               'nombre_nora': 'text',
               'notas': 'nullable',
               'rfc': 'nullable',
               'telefono': 'string_numeric',
               'ultimo_mensaje': 'timestamp'},
 'curso_inscripciones': {'estructura': 'tabla_vacia'},
 'cursos': {'activo': 'boolean',
            'categoria': 'text',
            'contenido_detalle': 'timestamp',
            'descripcion': 'text',
            'direccion': 'text',
            'duracion_horas': 'integer',
            'estudiantes_inscritos': 'integer',
            'fecha_actualizacion': 'timestamp',
            'fecha_creacion': 'timestamp',
            'fecha_fin': 'date',
            'fecha_inicio': 'date',
            'google_maps_link': 'text',
            'horario_domingo': 'text',
            'horario_jueves': 'text',
            'horario_lunes': 'text',
            'horario_martes': 'text',
            'horario_miercoles': 'text',
            'horario_sabado': 'text',
            'horario_viernes': 'text',
            'id': 'text',
            'instructor': 'text',
            'max_estudiantes': 'integer',
            'modalidad': 'text',
            'nivel': 'text',
            'nombre_nora': 'text',
            'objetivos': 'text',
            'precio': 'numeric',
            'precio_pronto_pago': 'numeric',
            'requisitos': 'text',
            'titulo': 'text'},
 'empresa_accesos': {'actualizado_en': 'timestamp',
                     'creado_en': 'timestamp',
                     'email': 'nullable',
                     'empresa_id': 'text',
                     'id': 'text',
                     'notas': 'text',
                     'password': 'text',
                     'plataforma': 'text',
                     'usuario': 'text'},
 'empresa_documentos': {'creado_en': 'timestamp',
                        'empresa_id': 'text',
                        'id': 'text',
                        'nombre': 'text',
                        'url': 'text'},
 'envios_programados': {'estructura': 'tabla_vacia'},
 'estudiantes': {'estructura': 'tabla_vacia'},
 'estudiantes_cursos': {'activo': 'boolean',
                        'direccion': 'text',
                        'edad': 'nullable',
                        'email': 'text',
                        'fecha_actualizacion': 'timestamp',
                        'fecha_creacion': 'timestamp',
                        'fecha_nacimiento': 'nullable',
                        'id': 'text',
                        'nombre_completo': 'text',
                        'nombre_nora': 'text',
                        'profesion_ocupacion': 'text',
                        'telefono': 'text'},
 'etiquetas': {'activa': 'boolean',
               'color': 'nullable',
               'etiqueta': 'nullable',
               'id': 'text',
               'nombre': 'text',
               'nombre_nora': 'text'},
 'etiquetas_nora': {'creado_en': 'timestamp',
                    'etiqueta': 'text',
                    'id': 'text',
                    'modulo': 'text',
                    'nombre_nora': 'text'},
 'facebook_paginas': {'access_token': 'nullable',
                      'access_token_valido': 'boolean',
                      'activa': 'boolean',
                      'actualizado_en': 'timestamp',
                      'categoria': 'text',
                      'ciudad': 'nullable',
                      'creado_en': 'timestamp',
                      'descripcion': 'text',
                      'direccion': 'nullable',
                      'email': 'text',
                      'empresa': 'nullable',
                      'empresa_id': 'nullable',
                      'estado_webhook': 'text',
                      'foto_perfil_url': 'timestamp',
                      'foto_portada_url': 'text',
                      'id': 'integer',
                      'likes': 'integer',
                      'nombre_cliente': 'nullable',
                      'nombre_pagina': 'text',
                      'page_id': 'string_numeric',
                      'pais': 'nullable',
                      'permisos_disponibles': 'nullable',
                      'seguidores': 'integer',
                      'telefono': 'nullable',
                      'ultima_sincronizacion': 'timestamp',
                      'username': 'text',
                      'verificada': 'boolean',
                      'website': 'text'},
 'funciones_automatizables': {'activa': 'boolean',
                              'actualizado_en': 'timestamp',
                              'archivo_origen': 'text',
                              'categoria': 'text',
                              'codigo_fuente': 'timestamp',
                              'creado_en': 'timestamp',
                              'descripcion': 'text',
                              'docstring': 'text',
                              'ejemplo_uso': 'json',
                              'envia_notificacion': 'boolean',
                              'es_automatizable': 'boolean',
                              'id': 'text',
                              'linea_inicio': 'integer',
                              'metodo_deteccion': 'text',
                              'modulo': 'text',
                              'nombre_funcion': 'text',
                              'parametros': 'json',
                              'ruta_completa': 'text',
                              'ruta_modulo_python': 'text',
                              'tipo_archivo': 'text'},
 'google_ads_config': {'access_token': 'nullable',
                       'activo': 'boolean',
                       'client_id': 'text',
                       'client_secret': 'text',
                       'cliente_id': 'nullable',
                       'created_at': 'timestamp',
                       'developer_token': 'text',
                       'developer_token_valid': 'boolean',
                       'expires_in': 'integer',
                       'id': 'text',
                       'login_customer_id': 'string_numeric',
                       'refresh_token': 'text',
                       'refresh_token_valid': 'boolean',
                       'token_type': 'text',
                       'updated_at': 'timestamp',
                       'user_id': 'nullable'},
 'google_ads_cuentas': {'accesible': 'boolean',
                        'account_status': 'integer',
                        'activa': 'boolean',
                        'ads_activos': 'integer',
                        'anuncios_activos': 'integer',
                        'conectada': 'boolean',
                        'created_at': 'timestamp',
                        'customer_id': 'string_numeric',
                        'empresa_id': 'text',
                        'es_test': 'boolean',
                        'fecha_actualizacion': 'timestamp',
                        'fecha_creacion': 'timestamp',
                        'id': 'integer',
                        'moneda': 'text',
                        'nombre_cliente': 'text',
                        'nombre_visible': 'text',
                        'problema': 'nullable',
                        'updated_at': 'timestamp',
                        'zona_horaria': 'text'},
 'google_ads_palabras_clave': {'campaña': 'text',
                               'clics': 'string_numeric',
                               'clics_num': 'integer',
                               'codigo_moneda': 'text',
                               'conversion_rate': 'numeric',
                               'conversion_value': 'numeric',
                               'conversiones': 'text',
                               'conversiones_num': 'numeric',
                               'costo': 'text',
                               'costo_num': 'numeric',
                               'costo_por_conversion': 'text',
                               'cpc_promedio': 'text',
                               'cpc_promedio_num': 'numeric',
                               'ctr': 'text',
                               'ctr_num': 'numeric',
                               'customer_id': 'string_numeric',
                               'empresa_id': 'nullable',
                               'estado': 'text',
                               'estado_palabra_clave': 'text',
                               'grupo_anuncios': 'text',
                               'id': 'integer',
                               'id_campaña': 'integer',
                               'id_grupo_anuncios': 'integer',
                               'id_palabra_clave': 'integer',
                               'impresiones': 'string_numeric',
                               'impresiones_num': 'integer',
                               'motivos_estado': 'nullable',
                               'nombre_cuenta': 'text',
                               'nombre_nora': 'text',
                               'palabra_clave': 'text',
                               'porcentaje_conversion': 'text',
                               'tipo_concordancia': 'text',
                               'url_final': 'text',
                               'url_final_movil': 'text'},
 'google_ads_reporte_anuncios': {'calidad_anuncio': 'nullable',
                                 'campaña': 'text',
                                 'clics': 'string_numeric',
                                 'codigo_moneda': 'text',
                                 'conversiones': 'string_numeric',
                                 'costo': 'text',
                                 'costo_por_conversion': 'text',
                                 'cpc_promedio': 'text',
                                 'ctr': 'text',
                                 'customer_id': 'string_numeric',
                                 'descripcion_1': 'text',
                                 'descripcion_2': 'text',
                                 'descripcion_3': 'text',
                                 'descripcion_4': 'nullable',
                                 'empresa_id': 'nullable',
                                 'estado': 'text',
                                 'estado_anuncio': 'text',
                                 'grupo_anuncios': 'text',
                                 'id_anuncio': 'string_numeric',
                                 'id_campaña': 'string_numeric',
                                 'id_grupo_anuncios': 'string_numeric',
                                 'impresiones': 'string_numeric',
                                 'mejoras_efectividad': 'nullable',
                                 'motivos_estado': 'nullable',
                                 'nombre_nora': 'text',
                                 'param_personalizado': 'nullable',
                                 'plantilla_seguimiento': 'nullable',
                                 'porcentaje_conversion': 'text',
                                 'pos_desc_1': 'string_numeric',
                                 'pos_desc_2': 'string_numeric',
                                 'pos_desc_3': 'string_numeric',
                                 'pos_desc_4': 'nullable',
                                 'pos_titulo_1': 'string_numeric',
                                 'pos_titulo_10': 'nullable',
                                 'pos_titulo_11': 'nullable',
                                 'pos_titulo_12': 'nullable',
                                 'pos_titulo_13': 'nullable',
                                 'pos_titulo_14': 'nullable',
                                 'pos_titulo_15': 'nullable',
                                 'pos_titulo_2': 'string_numeric',
                                 'pos_titulo_3': 'string_numeric',
                                 'pos_titulo_4': 'string_numeric',
                                 'pos_titulo_5': 'string_numeric',
                                 'pos_titulo_6': 'nullable',
                                 'pos_titulo_7': 'nullable',
                                 'pos_titulo_8': 'nullable',
                                 'pos_titulo_9': 'nullable',
                                 'ruta_1': 'text',
                                 'ruta_2': 'text',
                                 'sufijo_url_final': 'nullable',
                                 'tipo_anuncio': 'text',
                                 'titulo_1': 'text',
                                 'titulo_10': 'nullable',
                                 'titulo_11': 'nullable',
                                 'titulo_12': 'nullable',
                                 'titulo_13': 'nullable',
                                 'titulo_14': 'nullable',
                                 'titulo_15': 'nullable',
                                 'titulo_2': 'text',
                                 'titulo_3': 'text',
                                 'titulo_4': 'text',
                                 'titulo_5': 'text',
                                 'titulo_6': 'nullable',
                                 'titulo_7': 'nullable',
                                 'titulo_8': 'nullable',
                                 'titulo_9': 'nullable',
                                 'url_final': 'text',
                                 'url_final_movil': 'nullable'},
 'google_calendar_sync': {'estructura': 'tabla_vacia'},
 'historial_conversaciones': {'emisor': 'nullable',
                              'hora': 'nullable',
                              'ia_activada': 'boolean',
                              'id': 'text',
                              'mensaje': 'text',
                              'nombre': 'nullable',
                              'nombre_nora': 'nullable',
                              'origen': 'string_numeric',
                              'telefono': 'string_numeric',
                              'timestamp': 'timestamp',
                              'tipo': 'text'},
 'inscripciones_cursos': {'calificacion_final': 'nullable',
                          'comentarios': 'text',
                          'curso_id': 'text',
                          'estado_inscripcion': 'text',
                          'estudiante_id': 'text',
                          'fecha_cancelacion': 'nullable',
                          'fecha_completacion': 'nullable',
                          'fecha_inscripcion': 'timestamp',
                          'fecha_pago': 'nullable',
                          'id': 'text',
                          'metodo_pago': 'text',
                          'monto_pagado': 'numeric',
                          'motivo_cancelacion': 'nullable',
                          'nombre_nora': 'text'},
 'landing_pages_bloques': {'activo': 'boolean',
                           'actualizado_en': 'timestamp',
                           'creado_en': 'timestamp',
                           'css_classes': 'nullable',
                           'descripcion': 'text',
                           'html_template': 'text',
                           'id': 'integer',
                           'nombre': 'text',
                           'orden': 'integer',
                           'tipo': 'text'},
 'landing_pages_config': {'estructura': 'tabla_vacia'},
 'logs_errores': {'archivo': 'nullable',
                  'dato_extra': 'nullable',
                  'detalles': 'nullable',
                  'fecha': 'timestamp',
                  'fecha_error': 'timestamp',
                  'id': 'text',
                  'mensaje': 'text',
                  'nombre_nora': 'nullable',
                  'origen': 'text',
                  'tipo': 'nullable'},
 'logs_webhooks_meta': {'actualizado_en': 'timestamp',
                        'campo': 'text',
                        'creado_en': 'timestamp',
                        'datos_adicionales': 'nullable',
                        'error_procesamiento': 'nullable',
                        'id': 'integer',
                        'id_cuenta_publicitaria': 'nullable',
                        'nombre_nora': 'nullable',
                        'objeto_id': 'text',
                        'procesado': 'boolean',
                        'procesado_en': 'nullable',
                        'recibido_en': 'timestamp',
                        'timestamp': 'timestamp',
                        'tipo_objeto': 'text',
                        'valor': 'string_numeric'},
 'memoria': {'estructura': 'tabla_vacia'},
 'menus_conocimiento': {'estructura': 'tabla_vacia'},
 'meta_ads_anuncios_detalle': {'actions': 'nullable',
                               'activo': 'boolean',
                               'ad_id': 'string_numeric',
                               'add_to_cart': 'integer',
                               'alcance': 'integer',
                               'campana_id': 'string_numeric',
                               'clicks': 'integer',
                               'comments': 'nullable',
                               'conjunto_id': 'string_numeric',
                               'cost_per_10_sec_video_view': 'nullable',
                               'cost_per_1k_impressions': 'numeric',
                               'cost_per_2_sec_continuous_video_view': 'nullable',
                               'cost_per_action_type': 'nullable',
                               'cost_per_click': 'nullable',
                               'cost_per_estimated_ad_recallers': 'nullable',
                               'cost_per_inline_link_click': 'nullable',
                               'cost_per_lead': 'integer',
                               'cost_per_link_click': 'integer',
                               'cost_per_messaging_conversation_started': 'nullable',
                               'cost_per_outbound_click': 'nullable',
                               'cost_per_purchase': 'integer',
                               'cost_per_thruplay': 'nullable',
                               'cost_per_unique_click': 'nullable',
                               'cost_per_unique_inline_link_click': 'nullable',
                               'cost_per_unique_link_click': 'nullable',
                               'cost_per_unique_outbound_click': 'nullable',
                               'cpc': 'numeric',
                               'ctr': 'numeric',
                               'estimated_ad_recall_rate': 'nullable',
                               'estimated_ad_recallers': 'nullable',
                               'fecha_fin': 'date',
                               'fecha_inicio': 'date',
                               'fecha_reporte': 'nullable',
                               'fecha_sincronizacion': 'timestamp',
                               'fecha_ultima_actualizacion': 'timestamp',
                               'frequency': 'numeric',
                               'id': 'integer',
                               'id_cuenta_publicitaria': 'string_numeric',
                               'importe_gastado': 'numeric',
                               'impresiones': 'integer',
                               'initiate_checkout': 'integer',
                               'inline_link_clicks': 'integer',
                               'interacciones': 'integer',
                               'landing_page_views': 'integer',
                               'link_clicks': 'integer',
                               'messaging_conversations_started': 'nullable',
                               'nombre_anuncio': 'text',
                               'nombre_campana': 'text',
                               'nombre_conjunto': 'text',
                               'objetivo_campana': 'nullable',
                               'outbound_clicks': 'nullable',
                               'outbound_clicks_ctr': 'nullable',
                               'page_engagement': 'nullable',
                               'page_likes': 'integer',
                               'post_comments': 'nullable',
                               'post_engagement': 'nullable',
                               'post_engagements': 'integer',
                               'post_likes': 'integer',
                               'post_reactions': 'nullable',
                               'post_shares': 'nullable',
                               'preview_url': 'nullable',
                               'publisher_platform': 'text',
                               'purchase_roas': 'nullable',
                               'quality_ranking': 'nullable',
                               'reproducciones_video_3s': 'integer',
                               'saves': 'nullable',
                               'shares': 'nullable',
                               'status': 'text',
                               'status_campana': 'nullable',
                               'status_conjunto': 'nullable',
                               'thruplay_rate': 'nullable',
                               'thruplays': 'nullable',
                               'unique_clicks': 'nullable',
                               'unique_ctr': 'nullable',
                               'unique_impressions': 'nullable',
                               'unique_inline_link_clicks': 'nullable',
                               'unique_link_clicks': 'nullable',
                               'unique_outbound_clicks': 'nullable',
                               'video_30s_watched': 'integer',
                               'video_avg_time_watched_actions': 'nullable',
                               'video_avg_watch_time_secs': 'nullable',
                               'video_completion_rate': 'nullable',
                               'video_p100_watched': 'integer',
                               'video_p25_watched': 'integer',
                               'video_p50_watched': 'integer',
                               'video_p75_watched': 'integer',
                               'video_play_actions': 'nullable',
                               'video_plays': 'nullable',
                               'video_plays_15s': 'nullable',
                               'video_plays_at_100': 'nullable',
                               'video_plays_at_25': 'nullable',
                               'video_plays_at_50': 'nullable',
                               'video_plays_at_75': 'nullable',
                               'video_views': 'integer',
                               'website_ctr': 'nullable',
                               'website_purchase_roas': 'nullable'},
 'meta_ads_audiencias': {'ad_account_id': 'string_numeric',
                         'audience_id': 'text',
                         'creada_en': 'timestamp',
                         'created_at': 'timestamp',
                         'estado': 'text',
                         'id': 'text',
                         'nombre_audiencia': 'text',
                         'nombre_nora': 'text',
                         'origen': 'text',
                         'tamaño_aproximado': 'nullable',
                         'tipo_audiencia': 'text'},
 'meta_ads_automatizaciones': {'estructura': 'tabla_vacia'},
 'meta_ads_campanas_avanzadas': {'estructura': 'tabla_vacia'},
 'meta_ads_conjuntos_avanzados': {'estructura': 'tabla_vacia'},
 'meta_ads_creativos': {'estructura': 'tabla_vacia'},
 'meta_ads_cuentas': {'account_status': 'integer',
                      'actualizada_en': 'timestamp',
                      'ad_account_id': 'nullable',
                      'ads_activos': 'integer',
                      'conectada': 'boolean',
                      'correo': 'nullable',
                      'created_at': 'timestamp',
                      'empresa_id': 'text',
                      'estado_actual': 'text',
                      'id': 'integer',
                      'id_cuenta_publicitaria': 'string_numeric',
                      'nombre_cliente': 'text',
                      'nombre_nora': 'text',
                      'nombre_visible': 'text',
                      'tipo_plataforma': 'text',
                      'ultima_notificacion': 'timestamp',
                      'webhook_registrado': 'boolean'},
 'meta_ads_disenos_empresas': {'estructura': 'tabla_vacia'},
 'meta_ads_disenos_reportes': {'actualizado_en': 'timestamp',
                               'bg_color': 'text',
                               'creado_en': 'timestamp',
                               'header_color': 'text',
                               'id': 'text',
                               'nombre_diseno': 'text',
                               'nombre_nora': 'text',
                               'variables': 'array'},
 'meta_ads_logs_cambios': {'estructura': 'tabla_vacia'},
 'meta_ads_pixeles': {'estructura': 'tabla_vacia'},
 'meta_ads_prereportes': {'estructura': 'tabla_vacia'},
 'meta_ads_reportes': {'estructura': 'tabla_vacia'},
 'meta_ads_reportes_compartidos': {'activo': 'boolean',
                                   'compartido_por': 'text',
                                   'created_at': 'timestamp',
                                   'empresa_nombre': 'text',
                                   'id': 'text',
                                   'periodo': 'text',
                                   'reporte_id': 'text',
                                   'token': 'text'},
 'meta_ads_reportes_config': {'estructura': 'tabla_vacia'},
 'meta_ads_reportes_semanales': {'alcance': 'integer',
                                 'archivado_en': 'timestamp',
                                 'clicks': 'integer',
                                 'created_at': 'timestamp',
                                 'delivery_activos': 'nullable',
                                 'delivery_inactivos': 'nullable',
                                 'empresa_id': 'text',
                                 'empresa_nombre': 'text',
                                 'estatus': 'text',
                                 'facebook_alcance': 'integer',
                                 'facebook_clicks': 'integer',
                                 'facebook_importe_gastado': 'numeric',
                                 'facebook_impresiones': 'integer',
                                 'facebook_mensajes': 'integer',
                                 'fecha_fin': 'date',
                                 'fecha_inicio': 'date',
                                 'id': 'text',
                                 'id_cuenta_publicitaria': 'string_numeric',
                                 'importe_gastado_anuncios': 'numeric',
                                 'importe_gastado_campañas': 'numeric',
                                 'importe_gastado_conjuntos': 'numeric',
                                 'impresiones': 'integer',
                                 'instagram_alcance': 'integer',
                                 'instagram_clicks': 'integer',
                                 'instagram_importe_gastado': 'numeric',
                                 'instagram_impresiones': 'integer',
                                 'instagram_mensajes': 'integer',
                                 'interacciones': 'integer',
                                 'link_clicks': 'integer',
                                 'mensajes': 'integer',
                                 'nombre_nora': 'text',
                                 'public_token': 'text',
                                 'reproducciones_video_3s': 'integer',
                                 'total_anuncios': 'integer',
                                 'total_campañas': 'integer',
                                 'total_conjuntos': 'integer',
                                 'video_plays': 'integer'},
 'meta_ads_videos': {'estructura': 'tabla_vacia'},
 'meta_anuncios_automatizados': {'estructura': 'tabla_vacia'},
 'meta_plantillas_anuncios': {'activa': 'boolean',
                              'actualizada_en': 'timestamp',
                              'creada_en': 'timestamp',
                              'descripcion': 'text',
                              'id': 'integer',
                              'nombre': 'text',
                              'nombre_nora': 'text',
                              'plantilla_json': 'json'},
 'meta_publicaciones_webhook': {'creada_en': 'timestamp',
                                'created_time': 'integer',
                                'id': 'integer',
                                'mensaje': 'text',
                                'page_id': 'string_numeric',
                                'post_id': 'text',
                                'procesada': 'boolean',
                                'procesada_en': 'timestamp',
                                'tipo_item': 'text',
                                'webhook_data': 'text'},
 'meta_webhook_eventos': {'estructura': 'tabla_vacia'},
 'modulos_disponibles': {'archivo_principal': 'nullable',
                         'descripcion': 'text',
                         'icono': 'text',
                         'id': 'text',
                         'nombre': 'text',
                         'ruta': 'text'},
 'niveles_cursos': {'activo': 'boolean',
                    'descripcion': 'text',
                    'fecha_creacion': 'timestamp',
                    'id': 'text',
                    'nombre': 'text',
                    'nombre_nora': 'text',
                    'orden_dificultad': 'integer'},
 'pagos': {'cliente_id': 'text',
           'concepto': 'text',
           'empresa_id': 'text',
           'estatus': 'text',
           'fecha_pago': 'nullable',
           'fecha_vencimiento': 'date',
           'forma_pago_id': 'text',
           'formato': 'text',
           'id': 'text',
           'monto': 'numeric',
           'nombre_nora': 'text',
           'notas': 'text',
           'periodicidad': 'nullable',
           'tipo': 'text'},
 'pagos_cursos': {'estructura': 'tabla_vacia'},
 'pagos_items': {'cantidad': 'numeric',
                 'costo_unit': 'numeric',
                 'created_at': 'timestamp',
                 'id': 'text',
                 'nombre': 'timestamp',
                 'pago_id': 'text',
                 'servicio_id': 'nullable'},
 'planeaciones_clips': {'estructura': 'tabla_vacia'},
 'planeaciones_contenido': {'created_at': 'timestamp',
                            'duracion_estimada_min': 'integer',
                            'empresa_id': 'text',
                            'fecha_grabacion': 'date',
                            'hora_inicio': 'text',
                            'id': 'text',
                            'logistica': 'nullable',
                            'nombre_nora': 'text',
                            'num_contenidos': 'integer',
                            'objetivo': 'text',
                            'postproduccion': 'nullable',
                            'preproduccion': 'nullable',
                            'titulo': 'text'},
 'planeaciones_postproduccion': {'estructura': 'tabla_vacia'},
 'planeaciones_produccion': {'estructura': 'tabla_vacia'},
 'planeaciones_sharing': {'estructura': 'tabla_vacia'},
 'planeaciones_temas': {'estructura': 'tabla_vacia'},
 'plantillas_tareas': {'estructura': 'tabla_vacia'},
 'presupuestos': {'estructura': 'tabla_vacia'},
 'presupuestos_items': {'estructura': 'tabla_vacia'},
 'proyectos_subidos': {'estructura': 'tabla_vacia'},
 'reservas_airbnb': {'estructura': 'tabla_vacia'},
 'respuestas_bot': {'creado_en': 'timestamp',
                    'id': 'text',
                    'nombre_nora': 'nullable',
                    'palabra_clave': 'text',
                    'respuesta': 'text'},
 'reuniones_clientes': {'cliente_id': 'text',
                        'creado_en': 'nullable',
                        'empresa_id': 'text',
                        'fecha_hora': 'timestamp',
                        'id': 'text',
                        'minuta': 'text',
                        'participantes': 'text'},
 'rutas_registradas': {'blueprint': 'text',
                       'creado_en': 'nullable',
                       'id': 'text',
                       'metodo': 'text',
                       'registrado_en': 'timestamp',
                       'ruta': 'text'},
 'servicios': {'categoria': 'text',
               'costo': 'numeric',
               'descripcion': 'text',
               'id': 'text',
               'nombre_nora': 'text',
               'tipo': 'text',
               'titulo': 'text'},
 'subtareas': {'activo': 'boolean',
               'asignada_a_empresa': 'boolean',
               'creado_por': 'text',
               'created_at': 'timestamp',
               'descripcion': 'text',
               'empresa_id': 'text',
               'estatus': 'text',
               'fecha_limite': 'date',
               'id': 'text',
               'prioridad': 'text',
               'tarea_padre_id': 'text',
               'titulo': 'text',
               'updated_at': 'timestamp',
               'usuario_empresa_id': 'text'},
 'subtareas_completadas': {'estructura': 'tabla_vacia'},
 'super_admins': {'activo': 'boolean',
                  'correo': 'text',
                  'id': 'text',
                  'nombre': 'text',
                  'password': 'text'},
 'tarea_comentarios': {'estructura': 'tabla_vacia'},
 'tareas': {'activo': 'boolean',
            'asignada_a_empresa': 'boolean',
            'codigo_tarea': 'text',
            'creado_por': 'text',
            'created_at': 'timestamp',
            'descripcion': 'text',
            'empresa_id': 'text',
            'estatus': 'text',
            'fecha_limite': 'nullable',
            'fecha_vencimiento': 'nullable',
            'id': 'text',
            'nombre_nora': 'text',
            'origen': 'text',
            'prioridad': 'text',
            'titulo': 'text',
            'updated_at': 'timestamp',
            'usuario_empresa_id': 'text'},
 'tareas_completadas': {'activo': 'boolean',
                        'asignada_a_empresa': 'boolean',
                        'codigo_tarea': 'text',
                        'creado_por': 'text',
                        'created_at': 'timestamp',
                        'descripcion': 'nullable',
                        'empresa_id': 'text',
                        'estatus': 'text',
                        'fecha_limite': 'date',
                        'id': 'text',
                        'nombre_nora': 'text',
                        'origen': 'nullable',
                        'prioridad': 'text',
                        'titulo': 'text',
                        'updated_at': 'timestamp',
                        'usuario_empresa_id': 'text'},
 'tareas_por_plantilla': {'estructura': 'tabla_vacia'},
 'tareas_recurrentes': {'active': 'boolean',
                        'count': 'nullable',
                        'created_at': 'timestamp',
                        'dtstart': 'timestamp',
                        'id': 'text',
                        'rrule': 'text',
                        'tarea_id': 'text',
                        'until': 'nullable',
                        'updated_at': 'timestamp'},
 'templates_tarea': {'estructura': 'tabla_vacia'},
 'tickets': {'estructura': 'tabla_vacia'},
 'twilio_logs': {'estado': 'text',
                 'fecha_envio': 'timestamp',
                 'from_number': 'text',
                 'id': 'text',
                 'mensaje': 'text',
                 'numero': 'text',
                 'sid': 'text'},
 'usuarios_clientes': {'activo': 'boolean',
                       'correo': 'text',
                       'crear_tareas_otros': 'boolean',
                       'created_at': 'timestamp',
                       'es_supervisor': 'boolean',
                       'es_supervisor_tareas': 'boolean',
                       'id': 'text',
                       'modulos': 'array',
                       'nombre': 'text',
                       'nombre_nora': 'text',
                       'password': 'text',
                       'reasignar_tareas': 'boolean',
                       'rol': 'text',
                       'telefono': 'string_numeric',
                       'updated_at': 'timestamp',
                       'ver_todas_tareas': 'boolean'},
 'vista_estadisticas_cursos': {'calificacion_promedio': 'nullable',
                               'cancelados': 'integer',
                               'categoria': 'text',
                               'completados': 'integer',
                               'estudiantes_inscritos': 'integer',
                               'id': 'text',
                               'ingresos_totales': 'numeric',
                               'inscritos_activos': 'integer',
                               'nombre_nora': 'text',
                               'precio': 'numeric',
                               'titulo': 'text'},
 'vista_inscripciones_completa': {'calificacion_final': 'nullable',
                                  'curso_categoria': 'text',
                                  'curso_id': 'text',
                                  'curso_modalidad': 'text',
                                  'curso_precio': 'numeric',
                                  'curso_titulo': 'text',
                                  'estado_inscripcion': 'text',
                                  'estudiante_email': 'text',
                                  'estudiante_id': 'text',
                                  'estudiante_nombre': 'text',
                                  'estudiante_profesion': 'text',
                                  'estudiante_telefono': 'text',
                                  'fecha_completacion': 'nullable',
                                  'fecha_inscripcion': 'timestamp',
                                  'inscripcion_id': 'text',
                                  'monto_pagado': 'numeric',
                                  'nombre_nora': 'text'},
 'whatsapp_mensajes': {'estructura': 'tabla_vacia'},
 'whatsapp_mensajes_pendientes': {'cuenta_id': 'nullable',
                                  'estado': 'text',
                                  'fecha_creacion': 'timestamp',
                                  'fecha_envio': 'nullable',
                                  'id': 'integer',
                                  'mensaje': 'text',
                                  'numero_destino': 'string_numeric'},
 'whatsapp_sessions': {'estructura': 'tabla_vacia'},
 'whatsapp_web_sessions': {'created_at': 'timestamp',
                           'estado': 'text',
                           'fecha_desconexion': 'nullable',
                           'fecha_generacion': 'timestamp',
                           'id': 'integer',
                           'nombre_nora': 'text',
                           'qr_code': 'text',
                           'session_id': 'text',
                           'updated_at': 'timestamp',
                           'whatsapp_url': 'text'}}
