create table public.meta_ads_reportes_semanales (
  id uuid not null default gen_random_uuid (),
  empresa_id uuid not null,
  id_cuenta_publicitaria text not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  total_campañas integer null,
  importe_gastado_campañas numeric null,
  total_conjuntos integer null,
  importe_gastado_conjuntos numeric null,
  total_anuncios integer null,
  importe_gastado_anuncios numeric null,
  impresiones integer null,
  alcance integer null,
  clicks integer null,
  link_clicks integer null,
  mensajes integer null,
  interacciones integer null,
  video_plays integer null,
  reproducciones_video_3s integer null,
  delivery_activos integer null,
  delivery_inactivos integer null,
  created_at timestamp without time zone null default now(),
  empresa_nombre text null,
  facebook_impresiones integer null,
  facebook_alcance integer null,
  facebook_clicks integer null,
  facebook_mensajes integer null,
  facebook_importe_gastado numeric null,
  instagram_impresiones integer null,
  instagram_alcance integer null,
  instagram_clicks integer null,
  instagram_mensajes integer null,
  instagram_importe_gastado numeric null,
  public_token text null,
  constraint meta_ads_reportes_semanales_pkey primary key (id),
  constraint meta_ads_reportes_cuenta_fkey foreign KEY (id_cuenta_publicitaria) references meta_ads_cuentas (id_cuenta_publicitaria),
  constraint meta_ads_reportes_empresa_fkey foreign KEY (empresa_id) references cliente_empresas (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists meta_ads_reportes_token_idx on public.meta_ads_reportes_semanales using btree (public_token) TABLESPACE pg_default;
